version: '3.8'

services:
  frontend:
    container_name: graphprojectmanager_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: graphprojectmanager_backend
    build: ./backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4000:4000"
    networks:
      - webapp

networks:
  webapp:
    driver: bridge
